project:
  type: website
  output-dir: docs

website:
  title: "beomdo's ML-DL blog"
  site-url: "https://beomdo-park.github.io"
  site-path: "/"
  description: "머신러닝, 데이터 분석, AI 블로그"
  open-graph: true

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "My Tech Stacks" # 드롭다운 메뉴 예시
        menu: # "My Tech Stacks"의 하위 메뉴로 들여쓰기
          - text: "Python"
            # href: "/posts/index.html?category=Python" # 카테고리별 필터링 링크 예시 (Quarto 1.4+ 스타일)
          - text: "Machine Learning"
            # href: "/posts/index.html?category=MachineLearning" # 카테고리별 필터링 링크 예시
    right:
      - icon: github
        href: https://github.com/beomdo-park

  page-footer:
    left: "© 2025, Beomdo-Park. Powered by Quarto."
    right:
      - icon: github
        href: https://github.com/beomdo-park/

format:
  html:
    include-in-header:
      text: |
        <meta name="google-site-verification" content="tQV_UbBEk_vL_s9vxCne2Yd0GPHJ4vn8s2pPhfV0PYo" />
        <meta name="naver-site-verification" content="6c1006d6edf85b99c51f1f82aabd2a4fd68ec739" />
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

    respect-user-color-scheme: true # 사용자 시스템 설정 존중

# editor: visual
