{
  "hash": "638b33e0401b80c37d447badc466e40d",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"[2026 ABC 프로젝트 멘토링 2기] 프로젝트 6주차 - 작은 게이트가 자동으로 손해 영역을 회피한다\"\ndescription: \"5주차에서 드러난 사전 디코더의 손해 영역을 학습으로 흡수하는 58.9k 파라미터 게이트를 설계하고, 분포 외 거리 15/17에서의 자동 회피와 27.7% 호출만으로 MWPM 단독보다 낮은 결합 LER에 도달하는 운용점을 측정합니다.\"\ndate: \"2026-05-10\"\nauthor: \"Beomdo Park\"\ncategories: [\"ABC프로젝트멘토링\", \"유클리드소프트\", \"고용노동부\", \"대한상공회의소\", \"미래내일일경험사업\", \"QEC\"]\ntags: [\"DispatchGate\", \"PreDecoder\", \"OOD\", \"Latency\", \"ParetoCurve\", \"SurfaceCode\"]\npage-layout: full\nfreeze: auto\njupyter:\n  kernelspec:\n    name: python3\n    display_name: Python 3\n    language: python\n---\n\n\n> 안녕하세요, ABC 프로젝트 멘토링 2기 ROQET 팀의 여섯 번째 기술노트입니다. 지난주는 *문제 발견* 이었고, 이번 주는 *해결책* 입니다. 5주차에서 NVIDIA Ising-Decoding의 균일 호출 가정이 거리 13/17에서 통계적으로 깨진다는 사실을 표와 forest plot으로 보였습니다. 이번 주는 그 손해 영역을 *학습으로 흡수* 하는 58.9k 파라미터 게이트를 설계하고, 분포 외 거리에서의 자동 회피와 운용점 Pareto 곡선까지 정직하게 들여다보겠습니다.\n\n::: {.callout-tip title=\"이전 포스트\"}\n- [1주차 포스트](/posts/project-roqet-01-gnn-quantization/) — GNN과 PTQ 개념 정리\n- [2주차 포스트](/posts/project-roqet-02-qec-stim-stabilizer/) — QEC 기본 동작과 Stim으로 신드롬 데이터 생성\n- [3주차 포스트](/posts/project-roqet-03-detector-graph-gnn/) — Annotated Detector Graph와 GNN 디코더 첫 학습\n- [4주차 포스트](/posts/project-roqet-04-edge-aware-decoder/) — 엣지 타입 분리 디코더와 MWPM 격차 측정\n- [5주차 포스트](/posts/project-roqet-05-predecoder-helpfulness/) — 사전 디코더 호출이 항상 도움일까? 균일 호출 가정의 측정\n:::\n\n---\n\n## 1. 5주차가 남긴 빈 칸\n\n지난 회차의 결론을 한 단락으로 압축하면 다음과 같습니다. 거리 5에서는 NN 사전 디코더가 분명히 이득(LER 비율 1.29~1.53), 거리 9에서는 무이득(비율 ≈ 0.98), 거리 13/17에서는 통계적으로 유의한 손해(비율 0.41~0.74)였습니다. 균일 호출은 이 모든 영역에 동일하게 4 µs를 지불하므로 *낭비* 와 *역효과* 가 동시에 발생합니다.\n\n빈 칸은 다음과 같이 정의됩니다. **\"손해 영역은 회피하면서 이득 영역에서는 호출을 살리는, 그러면서 단일 샷 지연시간을 늘리지 않는 메커니즘이 필요합니다.\"** 추가로 한 가지 제약이 있습니다. 거리 13/$p=6{\\times}10^{-3}$ 같은 셀에서는 다시 NN 이득이 회복되므로 *(거리, 오류율, 기저)* 의 단순 if-else로는 분리되지 않습니다. 결국 **신드롬 텐서 $X$ 자체를 보고** 호출/기각을 결정하는 학습된 분류기가 필요합니다.\n\n---\n\n## 2. 게이트 설계 한 장\n\n![선택적 호출 게이트 파이프라인. 신드롬 $X$가 사전 디코더 $f_\\theta$와 게이트 $g_\\phi$에 *동시에* 들어갑니다. 게이트 점수가 임계 $\\tau$를 넘으면 NN 보정된 신드롬이 MWPM으로(실선), 그렇지 않으면 원본 신드롬이 곧바로 MWPM으로(점선) 향합니다.](figs/architecture_compare-1.png){#fig-arch width=92%}\n\n게이트 $g_\\phi : \\mathbb{R}^{T \\times d \\times d \\times 4} \\rightarrow [0, 1]$의 구조는 다음과 같습니다.\n\n- **5층 3차원 합성곱 이진 분류기**, 은닉 폭 32, 합성곱 깊이 3\n- 적응형 전역 풀링으로 $(T, d)$ 의존성 제거 → 학습 시점과 다른 거리/라운드 수에도 *동일 가중치* 적용 가능\n- 총 파라미터 **58,881개**, NVIDIA Ising-Decoding (Fast)의 912,772개 대비 **약 1/15**\n\n설계의 핵심은 입력입니다. 게이트는 *사전 디코더의 출력* $f_\\theta(X)$가 아니라 **신드롬 텐서 $X$ 자체** 를 입력으로 받습니다. 이 결정 한 줄이 단일 샷 지연시간 회계 전체를 바꿉니다.\n\n::: {.callout-note title=\"왜 신드롬을 직접 입력으로 받나\"}\n게이트가 NN 출력을 봐야 한다면 결정 자체가 NN 호출 *후* 가능합니다. 이 경우 \"NN을 호출하지 않기로 결정한 샷\" 도 이미 NN을 한 번 돌린 뒤이므로 NN 회피의 의미가 사라집니다. 신드롬 직접 입력은 게이트와 사전 디코더를 **병렬로 실행** 가능하게 만들어, 게이트 비용이 단일 샷 지연시간에 *추가* 되지 않게 합니다.\n:::\n\n학습은 5주차에서 정의한 긍정 기여 라벨 $y_{\\mathrm{help}}$에 대한 이항 교차 엔트로피로 진행했습니다. 학습 분포는 6개 조건 ($d \\in \\{5, 9, 13\\} \\times p \\in \\{3{\\times}10^{-3}, 6{\\times}10^{-3}\\}$, $Z$ 기저), 조건당 10,000 학습/3,000 검증, AdamW(lr $10^{-3}$), 배치 128, 12 에폭, 시드 42. 양성 비율은 1.24% — 즉 학습 데이터의 98.76%가 *NN을 부르지 않아도 되는 신드롬* 입니다. 평가는 학습과 시드를 분리한 조건당 20,000 샷에서 수행했습니다.\n\n---\n\n## 3. 호출 정책\n\n추론 단계의 호출 정책은 임계 $\\tau$ 한 줄로 정의됩니다.\n\n$$\n\\pi_\\tau(X) = \\begin{cases} \\hat{\\ell}_{\\mathrm{NN}}(X) & z_\\phi(X) > \\tau, \\\\ \\hat{\\ell}_{\\mathrm{MWPM}}(X) & \\text{otherwise}, \\end{cases}\n$$\n\n여기서 $z_\\phi(X)$는 게이트의 로짓입니다. 두 극한이 의미를 명확히 해 줍니다. $\\tau \\to +\\infty$ 극한은 모든 샷에서 게이트가 기각하므로 **MWPM 단독** 과 같고, $\\tau \\to -\\infty$ 극한은 모든 샷에서 호출하므로 **NVIDIA의 상시 호출** 과 같습니다. 그 사이의 임계는 LER과 연산량의 균형 곡선, 즉 **Pareto 곡선** 을 그립니다.\n\n핵심은 게이트가 *학습 후* 어떤 임계에서도 손해 영역을 호출하지 않는 가중치로 수렴해야 한다는 것입니다. 다음 두 절이 이를 측정으로 확인합니다.\n\n---\n\n## 4. 결과 1: 무이득 영역에서의 자동 회피\n\n거리 9/$p=3{\\times}10^{-3}$ 조건은 학습 분포에 *포함된* 무이득 조건입니다. 균일 호출은 LER 0.00130에 4 µs/샷을 지불합니다. 한편 MWPM 단독 LER은 0.00095입니다. NN을 매번 부르는 것이 LER을 0.00035 늘리면서 비용까지 지불하는 셈입니다.\n\n학습된 게이트의 동작은 다음과 같습니다.\n\n- 게이트 로짓 분포가 *모든 양의 임계 아래* 에 놓입니다.\n- 결과적으로 모든 임계에서 **호출률 0%** 로 유지됩니다.\n- 결합 LER은 MWPM 단독 수준인 0.00095로 회복되고, 신경망 비용은 100% 절약됩니다.\n\n별도 if-else 규칙을 넣은 게 아닙니다. 학습이 끝난 시점의 게이트 가중치 자체가 이 영역의 신드롬에 대해 모두 음수 로짓을 출력합니다. 즉 *\"여기서는 NN을 부르지 마\"* 가 데이터로부터 학습된 결과입니다. 그리고 이 회피는 비학습 밀도 기준선(=양성 비율과 동일한 호출률을 임의 표본에 적용)에 비해 약 **4배 더 선택적** 입니다.\n\n---\n\n## 5. 결과 2: 이득 영역에서의 선택적 호출\n\n거리 5/$p=6{\\times}10^{-3}$ 조건은 5주차 표에서 비율 1.29로 NN 이득이 가장 큰 셀 중 하나였습니다. 이 영역에서는 게이트가 *기각이 아니라 선택적 호출* 모드로 동작해야 합니다.\n\n![임계 스윕에 따른 호출률–LER Pareto 곡선. 좌하단 모서리(낮은 호출률, 낮은 LER)가 운용점으로 가장 매력적인 영역입니다.](figs/fig_gate_alt.png){#fig-pareto width=88%}\n\n수치를 정리하면 다음과 같습니다.\n\n| 운용점 | 호출률 | 결합 LER | NN 비용 |\n|--------|--------|----------|---------|\n| MWPM 단독 ($\\tau \\to +\\infty$) | 0% | 0.0746 | 0 |\n| 게이트, $\\tau = -1.0$ | 22.8% | 0.0654 | ≈ 23% |\n| 게이트, $\\tau = -2.0$ | 27.7% | 0.0641 | ≈ 28% |\n| 상시 호출 ($\\tau \\to -\\infty$) | 100% | 0.0563 | 100% |\n\n핵심 한 줄: **27.7% 호출만으로 결합 LER이 MWPM 단독($0.0746$)보다 낮은 $0.0641$에 도달합니다.** 신경망 호출 비용은 약 72% 감소합니다. 상시 호출의 LER 0.0563에는 못 미치지만, *Pareto 우위* 운용점이 분명히 형성됩니다. \"가장 낮은 LER\" 만을 목표로 한다면 상시 호출이 여전히 최적이지만, \"한 µs라도 신경망 호출을 줄이고 싶다\" 는 운용 제약 아래에서는 게이트가 명확한 선택지가 됩니다.\n\n::: {#cell-pareto-points .cell execution_count=1}\n\n::: {#pareto-points .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>운용점</th>\n      <th>호출률(%)</th>\n      <th>결합 LER</th>\n      <th>NN 비용 절감(%)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>MWPM 단독</td>\n      <td>0.0</td>\n      <td>0.0746</td>\n      <td>100.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>게이트 τ=-1.0</td>\n      <td>22.8</td>\n      <td>0.0654</td>\n      <td>77.2</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>게이트 τ=-2.0</td>\n      <td>27.7</td>\n      <td>0.0641</td>\n      <td>72.3</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>상시 호출</td>\n      <td>100.0</td>\n      <td>0.0563</td>\n      <td>0.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n---\n\n## 6. 결과 3: 분포 외 거리에서의 일반화\n\n이번 회차에서 가장 인상적인 결과입니다. 게이트는 학습 분포 $d \\in \\{5, 9, 13\\}$만으로 학습되었습니다. 거리 15와 17 조건($p=3{\\times}10^{-3}$, 두 기저, 조건당 50,000 샷)은 학습에 *한 번도 등장하지 않은* 거리입니다. 5주차에서 확인했듯 이 영역은 LER 비율 0.41~0.61로 손해가 가장 깊은 영역이기도 합니다.\n\n같은 가중치를 적용한 결과는 다음과 같습니다.\n\n- 두 거리 모두에서 게이트 로짓 분포가 **−3 이하** 에 놓입니다.\n- 임계 $\\tau \\in [-3, 1]$의 어느 점에서도 **호출률 0%** 로 유지됩니다.\n- 따라서 손해 영역의 LER 증가가 *자동으로* 회피됩니다.\n\n이게 학습된 일반화의 신기한 부분입니다. 학습 데이터에는 거리 15/17이 없으므로 게이트는 \"이 거리에서는 NN을 쓰지 마\" 라고 *명시적으로* 배운 적이 없습니다. 그럼에도 학습된 가중치가 \"낮은 양성 비율\" 패턴을 신드롬 텐서로부터 일반화하면서, 학습 분포 밖의 손해 영역까지 함께 기각합니다. 즉 *\"NN이 도움 되는 신드롬은 어떻게 생겼는가\"* 를 게이트가 충분히 좁게 학습한 결과, 그 외 모든 신드롬을 자연스럽게 회피하는 형태로 수렴한 것입니다.\n\n이 결과의 운용적 함의는 분명합니다. 표면 부호는 거리를 늘려가며 운용되므로, 학습 시점의 거리 분포가 향후 운용 거리 분포의 *부분 집합* 일 가능성이 높습니다. 게이트가 이 외삽 영역에서 안전 측으로 동작한다는 사실은, 분포 외 환경에서 신경망이 잠재적으로 위험 요인이 되는 운용 시나리오에서 *기본 안전망* 역할을 할 수 있음을 시사합니다.\n\n---\n\n## 7. 지연 비용을 솔직하게\n\n![게이트가 추가될 때의 지연 비용 회계. 배치 평균과 단일 샷 지연시간을 분리해 표시합니다.](figs/latency_comparison-1.png){#fig-latency width=85%}\n\n게이트의 비용도 정직하게 적어야 합니다. RTX 5090 FP16, 배치 256, 거리 5, $T=9$ 환경에서 측정한 결과:\n\n- **게이트 자체 비용**: 한 샷당 0.67 µs\n- **호출률 5% 수준의 무이득 영역에서 배치 평균 비용**: 0.87 µs\n- **호출이 결정된 샷의 단일 지연시간**: 4.73 µs\n\n배치 평균 관점에서는 명확한 이득입니다. 무이득 영역에서 4 µs를 100% 절약하면서 게이트 비용 0.87 µs만 더하면, 순 절감이 약 3 µs 수준입니다. 다만 *단일 샷 마감 보장* 관점에서는 4.73 µs가 1 µs 사이클 한계를 초과하므로, 호출 샷의 마감 보장은 게이트만으로는 해결되지 않습니다. 본 회차는 이 한계를 *기록* 하는 데 그치고, speculative execution 같은 추가 파이프라인 설계는 향후 과제로 남깁니다.\n\n---\n\n## 8. 회고: ROQET 본 줄기와 사이드 트랙\n\n이번 5/6주차는 같은 QEC 도메인이지만 ROQET 본 줄기(GNN 디코더 vs MWPM)와는 다른 *사이드 트랙* 입니다. 본 줄기는 *디코더 자체* 를 신경망으로 대체해 MWPM이 잡지 못하는 정보를 잡으려는 방향이고, 사이드 트랙은 *기존 신경망 사전 디코더의 운용 정책* 을 학습된 게이트로 흡수하려는 방향입니다. 두 줄기는 서로를 대체하지 않고 보완합니다.\n\n7주차부터는 4주차 마지막에 약속드린 본 줄기 — *상관 잡음* 또는 *soft 신드롬* 으로 GNN이 우위를 가질 수 있는 regime을 만드는 실험 — 으로 돌아갑니다. 이번 회차의 게이트가 이미 학습된 신경망의 *호출 시점* 을 다뤘다면, 7주차는 신경망 *디코더 자체* 가 MWPM을 이길 수 있는 입력 조건을 만드는 작업이 됩니다.\n\n---\n\n## 9. 정리\n\n- **게이트 설계**: 5층 3D Conv, 58,881 파라미터, 신드롬 직접 입력 → 사전 디코더와 병렬 실행, 단일 샷 지연시간에 추가 비용 0.\n- **무이득 영역(거리 9)**: 호출률 0%로 자동 회피, MWPM 단독 LER 회복, 4 µs/샷 100% 절약.\n- **이득 영역(거리 5)**: 27.7% 호출만으로 결합 LER이 MWPM 단독보다 낮은 운용점 형성, NN 비용 약 72% 절감.\n- **분포 외 일반화(거리 15/17)**: 학습에 등장하지 않은 거리에서도 호출률 0% 유지, 손해 영역 자동 회피.\n- **지연 회계**: 배치 평균 0.87 µs(이득), 단일 샷 4.73 µs(1 µs 한계 초과 → 향후 과제).\n\n::: {.callout-note title=\"다음 주차 예고\"}\n7주차에서는 ROQET 본 줄기로 복귀합니다. 4주차 마지막에 약속드린 *상관 잡음 추가* 또는 *soft 신드롬* 셋업 중 하나를 우선 도입해, MWPM이 표현하지 못하는 정보가 들어왔을 때 GNN 디코더의 격차가 어떻게 변하는지 측정해 보겠습니다.\n:::\n\n---\n\n::: {.callout-tip title=\"참고 문헌\"}\n- Chamberland, C. et al. (2026). *Ising-Decoding: A Hardware-Aware Neural Pre-Decoder for Surface Codes.* NVIDIA Research.\n- Bausch, J. et al. (2024). *Learning to decode the surface code with a recurrent, transformer-based neural network.* Nature.\n- Higgott, O. & Gidney, C. (2025). *PyMatching v2: Sparse Blossom for fast minimum-weight perfect matching.* [github.com/oscarhiggott/PyMatching](https://github.com/oscarhiggott/PyMatching)\n- Gidney, C. (2021). *Stim: a fast stabilizer circuit simulator.* Quantum 5, 497.\n- Fowler, A. G. et al. (2012). *Surface codes: Towards practical large-scale quantum computation.* Phys. Rev. A 86, 032324.\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}