name: Publish Quarto Website to GitHub Pages

on:
  push:
    branches: [main] # main 브랜치에 푸시될 때마다 실행
  workflow_dispatch: # 수동 실행도 가능하도록

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # gh-pages 브랜치에 쓰기 위해 필요
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Nanum fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-nanum

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # 프로젝트에 맞는 Python 버전을 명시하세요 (예: '3.9', '3.10', '3.11')
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbformat scikit-learn pandas numpy matplotlib statsmodels seaborn

      # Quarto 렌더링 단계 추가 (publish 액션은 내부적으로 렌더링하지만 meta 태그 삽입을 위해 명시적으로 렌더링)
      - name: Render Quarto Project
        run: |
          quarto render

      # HTML 파일에 meta 태그 삽입
      - name: Insert meta tags
        run: |
          echo "Inserting meta tags to HTML files..."
          # index.html에 meta 태그 삽입
          sed -i 's|<meta charset="utf-8">|<meta charset="utf-8">\n<meta name="google-site-verification" content="tQV_UbBEk_vL_s9vxCne2Yd0GPHJ4vn8s2pPhfV0PYo">\n<meta name="naver-site-verification" content="6c1006d6edf85b99c51f1f82aabd2a4fd68ec739">|' docs/index.html

          # 변경 확인
          echo "Meta tags inserted successfully!"
          echo "First 20 lines of index.html:"
          head -n 20 docs/index.html

      - name: Publish to GitHub Pages (gh-pages branch)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages # 또는 output_dir을 docs로 하고 target: simple 지정
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
